SELECT '' AS GERADO,
'' AS LIBERADO,
'' AS ANEXO, 
gh.CD_ATENDIMENTO,
gh.NRO_GUIA,
gh.CD_SENHA,
gh.DT_AUTORIZACAO,
gh.NM_PACIENTE,
gh.NM_PRESTADOR,
gh.DT_REALIZACAO,
gh.NM_CONVENIO_CIR,
gh.EMAIL2,
gh.EMAIL3
FROM dbamv.VDIC_GUIAS_HONORARIOS gh
WHERE gh.CD_ATENDIMENTO LIKE '%3555084%'
AND gh.NM_PACIENTE LIKE '%%'
AND gh.NM_PRESTADOR LIKE '%%'
AND gh.CD_CONVENIO_CIR LIKE '%%'
