CREATE OR REPLACE VIEW VDIC_RESULTADOS_PAM AS
SELECT

--GERAL
tp.CD_TIP_PRESC, tp.DS_TIP_PRESC,
prod.CD_PRODUTO, prod.DS_PRODUTO,

--CLASSE FARMACOLOGICA
esp.CD_ESPECIE, esp.DS_ESPECIE,
cl.CD_CLASSE, cl.DS_CLASSE,
sc.CD_SUB_CLA, sc.DS_SUB_CLA,
pam.ANTIDOTOS,

--APRESENTACAO
prod.DS_PRODUTO AS APRES_DESCRICAO,
CASE
  WHEN prod.SN_ACONDICIONADO = 'S' THEN 'SIM'
  ELSE 'NÃO'
END AS APRES_ACONDICIONADO,
pam.APRES_TEMPERATURA,

--RECONSTITUICAO
pam.REC_DILUENTE,
pam.REC_RISCO,
pam.REC_ESTABILIDADE,

--DILUICAO
pam.DIL_INFUSAO,
pam.DIL_ESTABILIDADE,
pam.DIL_ARMAZENAMENTO,

--DOSE MAXIMA DIARIA
NULL AS DOSE_MAXIMA_ADULTO,
NULL AS DOSE_MAXIMA_PEDIATRICO,
NULL AS DOSE_MAXIMA_NEONATAL,
pam.AJUSTE_DOSE,

--VIA ADMINISTRACAO
NULL AS VIA_ADM_HABITUAL,
NULL AS VIA_ADM_TEMP_INFUSAO,
NULL AS VIA_ADM_DOSE_MAX_POSOLOGICA,
pam.VIA_ADM_RECOMENDACAO,
NULL AS VIA_ADM_DOSE_GRAVIDEZ,

--INCOMPATIBILIDADE E INTERACAO
pam.INCOMP_FARMACO_NUTRI,
NULL AS INCOMP_FARMACO_FARMACO,
pam.INCOMP_VIA_ADM,

--OUTROS
pam.REACOES_ADV,
pam.RECOMENDACOES_MANIPULACAO,
pam.REF_BIBLI

FROM dbamv.TIP_PRESC tp
LEFT JOIN dbamv.PRODUTO prod
  ON prod.CD_PRODUTO = tp.CD_PRODUTO
LEFT JOIN dbamv.SUB_CLAS sc
  ON sc.CD_SUB_CLA = prod.CD_SUB_CLA
  AND sc.CD_CLASSE = prod.CD_CLASSE
  AND sc.CD_ESPECIE = prod.CD_ESPECIE
LEFT JOIN dbamv.CLASSE cl
  ON cl.CD_CLASSE = prod.CD_CLASSE
  AND cl.CD_ESPECIE = prod.CD_ESPECIE
LEFT JOIN dbamv.ESPECIE esp
  ON esp.CD_ESPECIE = prod.CD_ESPECIE
--PAM
LEFT JOIN pocomed.PAM pam
  ON pam.CD_TIP_PRESC = tp.CD_TIP_PRESC
--WHERE tp.CD_TIP_PRESC = 22482
;
